package com.truckadvisor.dieselfaultadvisor.dto;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.util.List;

/**
 * Response DTO containing comprehensive fault code analysis
 * Generated by watsonx.ai Granite model
 */
@Data
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class FaultCodeAnalysis {
    
    /**
     * The complete fault code (e.g., "SPN 157 FMI 3")
     */
    private String faultCode;
    
    /**
     * Plain English explanation of what the fault code means
     */
    private String explanation;
    
    /**
     * List of common root causes for this fault
     */
    private List<String> rootCauses;
    
    /**
     * Step-by-step instructions to diagnose and fix the issue
     */
    private List<String> fixInstructions;
    
    /**
     * Tools needed to perform the repair
     */
    private List<String> toolsNeeded;
    
    /**
     * Parts that may need to be purchased
     */
    private List<String> partsToBuy;
    
    /**
     * Timestamp when the analysis was generated
     */
    private String timestamp;
}

// Made with Bob
